# ==================== how to configure ==================== 
# See /usr/share/examples/alacritty/alacritty.yml

window:
  dimensions:
    columns: 0
    lines: 0

  padding:
    x: 10
    y: 8

  dynamic_padding: true
  decorations: none
  startup_mode: Windowed
  title: Alacritty

  class:
    instance: Alacritty
    general: Alacritty

  gtk_theme_variant: None
  dynamic_title: false

scrolling:
  history: 10000
  multiplier: 3

font:
  normal:
    family: Hack Nerd Font
    style: Regular

  bold:
    family: Hack Nerd Font
    style: Bold

  italic:
    family: Hack Nerd Font
    style: Italic

  bold_italic:
    family: Hack Nerd Font
    style: Bold Italic
      
  size: 13.0

  offset:
    x: -1
    y: 1

  glyph_offset:
    x: 0
    y: 0

draw_bold_text_with_bright_colors: false

# color schemes
schemes:
  bananafish: &bananafish
    primary:
      background: '#373a3f'
      foreground: '#ebebeb'
    cursor:
      text: '#373a3f'
      cursor: '#ebebeb'
    vi_mode_cursor:
      text: '#373a3f'
      cursor: '#ebebeb'
    selection:
      text: CellForeground
      background: '#141415'
    search:
      matches:
        foreground: CellBackground
        background: '#aeecfb'
      bar:
        background: '#3e3f43'
        foreground: '#ebebeb'
    normal:
      black:   '#141415'
      red:     '#ed6e5b'
      green:   '#16bf94'
      yellow:  '#fbd100'
      blue:    '#648cf5'
      magenta: '#bd6dab'
      cyan:    '#aeecfb'
      white:   '#babbbf'
    bright:
      black:   '#141415'
      red:     '#ed6e5b'
      green:   '#16bf94'
      yellow:  '#fbd100'
      blue:    '#648cf5'
      magenta: '#bd6dab'
      cyan:    '#aeecfb'
      white:   '#fcfcfc'

  gruvbox_light: &gruvbox_light
    primary:
      # hard contrast: background = '#f9f5d7'
      # medium contrast background: '#fbf1c7'
      # soft contrast: background = '#f2e5bc'
      background: '#fbf1c7'
      foreground: '#3c3836'
    normal:
      black:   '#fbf1c7'
      red:     '#cc241d'
      green:   '#98971a'
      yellow:  '#d79921'
      blue:    '#458588'
      magenta: '#b16286'
      cyan:    '#689d6a'
      white:   '#7c6f64'
    bright:
      black:   '#928374'
      red:     '#9d0006'
      green:   '#79740e'
      yellow:  '#b57614'
      blue:    '#076678'
      magenta: '#8f3f71'
      cyan:    '#427b58'
      white:   '#3c3836'

  gruvbox_material_dark_soft: &gruvbox_material_dark_soft
    primary:
      background: '0x32302f'
      foreground: '0xd4be98'
    normal:
      black:   '0x45403d'
      red:     '0xea6962'
      green:   '0xa9b665'
      yellow:  '0xd8a657'
      blue:    '0x7daea3'
      magenta: '0xd3869b'
      cyan:    '0x89b482'
      white:   '0xd4be98'
    bright:
      black:   '0x45403d'
      red:     '0xea6962'
      green:   '0xa9b665'
      yellow:  '0xd8a657'
      blue:    '0x7daea3'
      magenta: '0xd3869b'
      cyan:    '0x89b482'
      white:   '0xd4be98'

  gruvbox_material_light_medium: &gruvbox_material_light_medium
    primary:
      background: '0xfbf1c7'
      foreground: '0x654735'
    normal:
      black:   '0x654735'
      red:     '0xc14a4a'
      green:   '0x6c782e'
      yellow:  '0xb47109'
      blue:    '0x45707a'
      magenta: '0x945e80'
      cyan:    '0x4c7a5d'
      white:   '0xeee0b7'
    bright:
      black:   '0x654735'
      red:     '0xc14a4a'
      green:   '0x6c782e'
      yellow:  '0xb47109'
      blue:    '0x45707a'
      magenta: '0x945e80'
      cyan:    '0x4c7a5d'
      white:   '0xeee0b7'

  forest-night: &forest-night
    primary:
      background: '0x323d43'
      foreground: '0xd8caac'
    normal:
      black:   '0x505a60'
      red:     '0xe68183'
      green:   '0xa7c080'
      yellow:  '0xd9bb80'
      blue:    '0x83b6af'
      magenta: '0xd39bb6'
      cyan:    '0x87c095'
      white:   '0xd8caac'
    bright:
      black:   '0x505a60'
      red:     '0xe68183'
      green:   '0xa7c080'
      yellow:  '0xd9bb80'
      blue:    '0x83b6af'
      magenta: '0xd39bb6'
      cyan:    '0x87c095'
      white:   '0xd8caac'
    
  onehalflight: &onehalflight
    primary:
      background: '0xfafafa'
      foreground: '0x383a42'
    normal:
      black: '0x383a42'
      red: '0xe45649'
      green: '0x50a14f'
      yellow: '0xc18401'
      blue: '0x0184bc'
      magenta: '0xa626a4'
      cyan: '0x0997b3'
      white: '0xfafafa'
    bright:
      black: '0x383a42'
      red: '0xe45649'
      green: '0x50a14f'
      yellow: '0xc18401'
      blue: '0x0184bc'
      magenta: '0xa626a4'
      cyan: '0x0997b3'
      white: '0xfafafa'

  onehalfdark: &onehalfdark
    primary:
      background: '0x282c34'
      foreground: '0xdcdfe4'
    normal:
      black: '0x282c34'
      red: '0xe06c75'
      green: '0x98c379'
      yellow: '0xe5c07b'
      blue: '0x61afef'
      magenta: '0xc678dd'
      cyan: '0x56b6c2'
      white: '0xdcdfe4'
    bright:
      black: '0x282c34'
      red: '0xe06c75'
      green: '0x98c379'
      yellow: '0xe5c07b'
      blue: '0x61afef'
      magenta: '0xc678dd'
      cyan: '0x56b6c2'
      white: '0xdcdfe4'

  PaperColorLight: &PaperColorLight
    primary:
      background: '0xeeeeee'
      foreground: '0x878787'
    cursor:
      text: '0xeeeeee'
      cursor: '0x878787'
    normal:
      black:   '0xeeeeee'
      red:     '0xaf0000'
      green:   '0x008700'
      yellow:  '0x5f8700'
      blue:    '0x0087af'
      magenta: '0x878787'
      cyan:    '0x005f87'
      white:   '0x444444'
    bright:
      black:   '0xbcbcbc'
      red:     '0xd70000'
      green:   '0xd70087'
      yellow:  '0x8700af'
      blue:    '0xd75f00'
      magenta: '0xd75f00'
      cyan:    '0x005faf'
      white:   '0x005f87'

  solarized_light: &solarized_light
    primary:
      background: '#fdf6e3' 
      foreground: '#657b83' 
    cursor:
      text:   '#fdf6e3' 
      cursor: '#657b83' 
    normal:
      black:   '#073642' 
      red:     '#dc322f' 
      green:   '#859900' 
      yellow:  '#b58900' 
      blue:    '#268bd2' 
      magenta: '#d33682' 
      cyan:    '#2aa198' 
      white:   '#eee8d5' 
    bright:
      black:   '#002b36' 
      red:     '#cb4b16' 
      green:   '#586e75' 
      yellow:  '#657b83' 
      blue:    '#839496' 
      magenta: '#6c71c4' 
      cyan:    '#93a1a1' 
      white:   '#fdf6e3' 

  solarized_dark: &solarized_dark
    primary:
      background: '#002b36' 
      foreground: '#839496' 
    cursor:
      text:   '#002b36' 
      cursor: '#839496' 
    normal:
      black:   '#073642' 
      red:     '#dc322f' 
      green:   '#859900' 
      yellow:  '#b58900' 
      blue:    '#268bd2' 
      magenta: '#d33682' 
      cyan:    '#2aa198' 
      white:   '#eee8d5' 
    bright:
      black:   '#002b36' 
      red:     '#cb4b16' 
      green:   '#586e75' 
      yellow:  '#657b83' 
      blue:    '#839496' 
      magenta: '#6c71c4' 
      cyan:    '#93a1a1' 
      white:   '#fdf6e3' 

colors: *onehalflight

background_opacity: 1.0

cursor:
  style: Block
  unfocused_hollow: true

live_config_reload: true

shell:
  program: /bin/bash
    
mouse:
  url:
    launcher:
      program: xdg-open
    modifiers: Control

key_bindings:
  - { key: V,        mods: Control|Shift, action: Paste            }
  - { key: C,        mods: Control|Shift, action: Copy             }
  - { key: Equals,   mods: Control,       action: IncreaseFontSize }
  - { key: Minus,    mods: Control,       action: DecreaseFontSize }
  - { key: L,         mods: Control, chars: "\x0c"                            }

log_level: Warn

