#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor eDP1 -d 1 2 3 4 5 6 7 8 9

bspc config border_width         4
bspc config window_gap           8

bspc config split_ratio          0.50
bspc config borderless_monocle   true 
bspc config gapless_monocle      true
bspc config focused_border_color '#282c34'
bspc config -d ^2 window_gap 0

bspc rule -a Firefox:Navigator desktop='^2' \
state=tiled follow=off focus=off \
border=off
bspc rule -a desktop='^2' split_ratio=0.80 
bspc rule -a Firefox:firefox state=floating
bspc rule -a Firefox:Firefox state=floating
bspc rule -a discord desktop='^9' state=tiled 
bspc rule -a TelegramDesktop desktop='^8' state=tiled
bspc rule -a TelegramDesktop:TelegramDesktop state=floating
bspc rule -a "Code - OSS" desktop='^3' state=tiled
bspc rule -a "Master PDF Editor 5" desktop='^4' state=tiled
bspc rule -a feh state=floating

xsetroot -cursor_name left_ptr

## another method for setting wallpaper, however, picom interferes and polybar doesn't appear on top of it
# xsetroot -bg "#323d43" -fg "#465258" -mod 16 16
~/.fehbg &

pgrep -x polybar > /dev/null || polybar heusc > /dev/null 2>&1 &

# redshift -P -O 4538

pgrep -x picom > /dev/null || picom --experimental-backends --config /home/devpogi/.config/picom/picom.conf &

#pgrep -x dunst > /dev/null || dunst &
#sleep 1;
#notify-send "Welcome" "$USER" -u low

## will be handled by cron job later
#notify-send "don't forget to run battery_health.sh" -u normal

